from __future__ import annotations


REGRESSION_CASES_FOOD_200 = [
    # =========================================================
    # 001-040 FATTY / FRIED / UPPER GI / SYSTEMIC
    # =========================================================
    {
        "id": "food_001",
        "text": "После жареной картошки и семечек подташнивает и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_002",
        "text": "После жирной еды слабость, сонливость и дурнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_003",
        "text": "После шашлыка и майонеза тяжесть и тошнота",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_004",
        "text": "После бургеров и чипсов болит голова и мутит",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_005",
        "text": "После очень жирного ужина переполненность, тяжесть и отрыжка",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_006",
        "text": "После жареного мяса и семечек ватное состояние и подташнивает",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_007",
        "text": "После фастфуда слабость и тянет ко сну",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_008",
        "text": "После жирной и жареной еды тяжесть вверху живота и тошнота",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_009",
        "text": "После картошки фри мутит и тяжело в желудке",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_010",
        "text": "После жареной курицы слабость и головная боль",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_011",
        "text": "После жирного плова тяжесть, тошнота и переполненность",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "simple_overeating", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_012",
        "text": "После жареных семечек болит голова и немного мутит",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_013",
        "text": "После орехов и жирной еды чувство камня в желудке",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_014",
        "text": "После шаурмы тяжесть, отрыжка и хочется лечь",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_015",
        "text": "После жареной рыбы подташнивает и сонливость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_016",
        "text": "После жирной пиццы тошнота и тяжесть под ложечкой",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_017",
        "text": "После еды на масле становится дурно и кружится голова",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_018",
        "text": "После жирного стейка тяжесть, отрыжка и слабость",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_019",
        "text": "После обильного ужина переполненность и тянет ко сну",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["simple_overeating", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_020",
        "text": "После очень тяжёлой еды тяжесть, тошнота и ватное состояние",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload", "simple_overeating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_021",
        "text": "После жареного и сладкого мутит и слабость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_022",
        "text": "После бургера и колы тяжесть в желудке и дурнота",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "simple_overeating", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_023",
        "text": "После жирных орехов и семечек подташнивает уже не первый раз",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_024",
        "text": "После картошки фри и майонеза под ложечкой тяжесть",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_025",
        "text": "После плотной жирной еды появилась отрыжка и переполненность",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_026",
        "text": "После жареной свинины тяжесть и тошнота уже пару раз",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_027",
        "text": "После бургеров болит голова и хочется спать",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_028",
        "text": "После жирного салата тяжесть и отрыжка воздухом",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_029",
        "text": "После жареной еды мутит и кружится голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_030",
        "text": "После жирного ужина тяжесть, слабость и небольшой озноб без температуры",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_031",
        "text": "После масла и жареной картошки тошнит и тяжесть вверху живота",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_032",
        "text": "После еды на ходу и фастфуда отрыжка и переполненность",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "functional_dyspepsia", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_033",
        "text": "После жирной еды ощущение, что желудок стоит",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_034",
        "text": "После семечек и чипсов стало мутно и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_035",
        "text": "После жирного ужина переполненность и хочется расстегнуть ремень",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_036",
        "text": "После орехов и жареного тяжело в желудке и мутит",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_037",
        "text": "После плотного жирного обеда болит голова и слабость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_038",
        "text": "После жареной курицы и соуса тяжесть и отрыжка",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_039",
        "text": "После очень жирного подташнивает и легкая слабость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_040",
        "text": "После переедания жирным тяжесть, отрыжка и сонливость",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },

    # =========================================================
    # 041-070 BILIARY / RUQ
    # =========================================================
    {
        "id": "food_041",
        "text": "После жирного тянет справа под ребром и горечь во рту",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_042",
        "text": "После жареной еды тяжесть справа под ребрами и тошнота",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_043",
        "text": "После масла и жирного сыра болит справа под ребром",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_044",
        "text": "После жирного мутит, горечь во рту и неприятно справа",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_045",
        "text": "После шашлыка боль справа под ребром и отдаёт в спину",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_046",
        "text": "После жирной еды сильная боль справа под ребром и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_047",
        "text": "После жирного снова тяжесть справа под ребром",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_048",
        "text": "После жареной картошки и яиц тянет справа и горечь",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_049",
        "text": "После сала тошнит и боль справа под ребром",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_050",
        "text": "После омлета и масла тяжесть справа и горько во рту",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_051",
        "text": "После жирного обеда справа под ребрами тянет уже не первый раз",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_052",
        "text": "После шашлыка мутит и неприятно справа под ребром",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_053",
        "text": "После жирной колбасы и сыра дискомфорт справа и тошнота",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_054",
        "text": "После сливочного торта неприятно справа под ребром",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_055",
        "text": "После жирного сразу горечь и тянущая боль справа",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_056",
        "text": "После жареного мяса справа тяжесть и рвота",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_057",
        "text": "После еды на масле сильная боль справа под ребрами",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_058",
        "text": "После жирного колет справа и горечь во рту каждый раз",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_059",
        "text": "После жирного боль справа, температура и тошнота",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_060",
        "text": "После яичницы и бекона тяжесть справа под ребром",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_061",
        "text": "После жирного снова горечь и дискомфорт справа",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_062",
        "text": "После оливье и мяса справа тянет и мутит",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_063",
        "text": "После жирного неприятно справа под ребрами и отдает в лопатку",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_064",
        "text": "После жареного тяжесть справа под ребром уже несколько месяцев",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_065",
        "text": "После масла боль справа и горечь, иногда подташнивает",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_066",
        "text": "После жирной еды справа под ребром боль и не могу разогнуться",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_067",
        "text": "После еды с майонезом горечь и тянет в правом подреберье",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_068",
        "text": "После жирного тошнота и правое подреберье беспокоит",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_069",
        "text": "После шашлыка боль справа под ребром, рвота и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_070",
        "text": "После жирного горечь и тяжесть справа почти каждый раз",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },

    # =========================================================
    # 071-100 REFLUX / DYSPEPSIA / UPPER GI
    # =========================================================
    {
        "id": "food_071",
        "text": "После позднего ужина жжение, кислая отрыжка и хуже когда ложусь",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_072",
        "text": "После еды изжога и кислый привкус во рту",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_073",
        "text": "После жирного жжение за грудиной и отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_074",
        "text": "После плотного ужина переполненность, отрыжка и жжение",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_075",
        "text": "После кофе и позднего ужина кислота и жжение в груди",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_076",
        "text": "После еды тяжесть под ложечкой и отрыжка",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_077",
        "text": "После небольшой еды быстрое насыщение и тяжесть",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_078",
        "text": "Ночью после еды жжение и кислая отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_079",
        "text": "После еды печет в груди и кислота во рту",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_080",
        "text": "После плотного ужина чувство переполнения и отрыжка воздухом",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_081",
        "text": "После еды под ложечкой тяжело и хочется расстегнуть одежду",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_082",
        "text": "После поздней пиццы ночью изжога и кислая отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_083",
        "text": "После еды переполненность и раннее насыщение уже давно",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_084",
        "text": "После жирного жжение, но боли нет",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_085",
        "text": "После еды горит в груди и отрыжка кислым",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_086",
        "text": "После ужина под ложечкой тяжесть и тошнота",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_087",
        "text": "После кофе и жирного изжога и жжение",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_088",
        "text": "После еды ощущение, что пища стоит в желудке",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_089",
        "text": "После небольшой порции быстро наедаюсь и тяжесть",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_090",
        "text": "После еды жжет и хуже если ложусь на спину",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_091",
        "text": "После еды тяжесть и отрыжка уже много недель",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_092",
        "text": "После еды ноет под ложечкой и тошнит",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "ulcer_or_gastritis_risk_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_093",
        "text": "После позднего сладкого ужина жжение и кислая отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_094",
        "text": "После алкоголя и жирной еды печет в груди",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_095",
        "text": "После ужина долго держится чувство переполнения",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_096",
        "text": "После еды жжение и кислая отрыжка почти каждый день",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_097",
        "text": "После еды подташнивает и тянет под ложечкой",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_098",
        "text": "После большой порции тяжесть под ложечкой без жжения",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_099",
        "text": "После еды жжение, отрыжка и кисло во рту",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_100",
        "text": "После ужина тяжесть и отрыжка с кислым привкусом",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },

    # =========================================================
    # 101-130 DAIRY / BOWEL / FODMAP / IBS
    # =========================================================
    {
        "id": "food_101",
        "text": "После молока и мороженого раздуло живот, урчит и жидкий стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_102",
        "text": "После творога вздутие и газы",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_103",
        "text": "После сливок и молочного коктейля урчание и понос",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_104",
        "text": "После йогурта вздуло живот и подташнивает",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_105",
        "text": "После молока крутит живот и жидкий стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_106",
        "text": "После мороженого живот бурлит и много газов",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_107",
        "text": "После творога каждый раз вздутие и урчание",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_108",
        "text": "После молочного стало плохо уже несколько раз",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_109",
        "text": "После лука и чеснока сильное вздутие и газы",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_110",
        "text": "После бобовых урчит, пучит и послабление стула",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_111",
        "text": "После яблочного сока вздутие и понос",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_112",
        "text": "После меда и фруктов бурлит живот и много газов",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_113",
        "text": "После фасоли вздутие и урчание весь вечер",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_114",
        "text": "После лука, чеснока и бобовых каждый раз раздувает живот",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_115",
        "text": "У меня часто после еды вздутие и постоянно меняется стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_116",
        "text": "Уже давно после разных продуктов вздутие и то запор то понос",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_117",
        "text": "Каждую неделю после еды крутит живот и меняется стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_118",
        "text": "Давно повторяется вздутие и нестабильный стул после еды",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_119",
        "text": "После сладкого йогурта бурлит и жидкий стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "carbohydrate_malabsorption_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_120",
        "text": "После лука в салате пучит и газы",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_121",
        "text": "После чеснока и фасоли урчание и живот как барабан",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_122",
        "text": "После молока и сливок каждый раз жидкий стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_123",
        "text": "После молочного коктейля газы и крутит живот",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_124",
        "text": "После яблок и меда урчание и понос",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_125",
        "text": "После фруктового сока вздуло живот",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_126",
        "text": "После разной еды часто вздутие и нестабильный стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_127",
        "text": "После сырников вздутие, урчание и много газов",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_128",
        "text": "После фасоли и лука жидкий стул и бурление",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_129",
        "text": "После молока живот бурлит уже несколько часов",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_130",
        "text": "После творога и сметаны понос и вздутие",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },

    # =========================================================
    # 131-160 HISTAMINE / ALCOHOL / SWEET / GLUCOSE / DEHYDRATION
    # =========================================================
    {
        "id": "food_131",
        "text": "После вина и сыра болит голова, краснеет лицо и сердце колотится",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_132",
        "text": "После копченостей и вина головная боль и покраснение лица",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_133",
        "text": "После шампанского и сыра тошнит, сердце стучит и жарко",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_134",
        "text": "После колбасы и вина болит голова и закладывает нос",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_135",
        "text": "После алкоголя тошнота и головная боль",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_136",
        "text": "После пива слабость и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "dehydration_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_137",
        "text": "После сладкого резко слабость, дрожь и потливость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_138",
        "text": "После торта дурнота и кружится голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_139",
        "text": "После сладкой газировки слабость и тошнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_140",
        "text": "После десерта после жирной еды мутит и дрожь",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_141",
        "text": "После еды слабость, сухость во рту и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["dehydration_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_142",
        "text": "После плотной еды ватное состояние и хочется лечь",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_143",
        "text": "После большого обеда слабость, сонливость и дурнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_144",
        "text": "После еды кружится голова и подташнивает, боли нет",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "dehydration_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_145",
        "text": "После вина и копченой колбасы лицо краснеет и болит голова",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_146",
        "text": "После сыра и шампанского закладывает нос и стучит сердце",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_147",
        "text": "После шоколада слабость и дрожь",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_148",
        "text": "После сладкого напитка потливость и дурнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_149",
        "text": "После алкоголя и жирной еды тошнит и слабость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_150",
        "text": "После пива и чипсов головная боль и сухость во рту",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "dehydration_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_151",
        "text": "После сладкого каждый раз слабость и хочется есть снова",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_152",
        "text": "После сыра и вина сердце колотится и лицо красное",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_153",
        "text": "После сладкого и кофе слабость и дрожь",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_154",
        "text": "После шампанского подташнивает и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_155",
        "text": "После торта и сладкой газировки слабость и потливость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_156",
        "text": "После еды будто сахара качает, дрожь и слабость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_157",
        "text": "После красного вина болит голова и жар в лице",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_158",
        "text": "После еды мало пил, сухость во рту и слабость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["dehydration_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_159",
        "text": "После сыра и копченостей болит голова и закладывает нос уже не раз",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_160",
        "text": "После алкоголя и сладкого дурнота и слабость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "sugar_glucose_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },

    # =========================================================
    # 161-200 URGENT / MIXED / EDGE / FALSE-POSITIVE DEFENSE
    # =========================================================
    {
        "id": "food_161",
        "text": "Рвота, понос, температура после подозрительной еды",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_162",
        "text": "После салата начались рвота и понос, температура 38",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_163",
        "text": "Сильная боль в животе, черный стул и слабость",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "food_164",
        "text": "После еды боль в груди и одышка",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "food_165",
        "text": "После еды обморок и слабость",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "food_166",
        "text": "После жирного неукротимая рвота и сильная боль",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_167",
        "text": "После еды кровь в рвоте",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "food_168",
        "text": "После подозрительной еды кровь в стуле и слабость",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "food_169",
        "text": "После жирного желтуха и боль справа",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_170",
        "text": "После еды не могу пить из-за рвоты",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_171",
        "text": "После еды сильная боль под ложечкой и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_172",
        "text": "После еды теряю сознание и очень плохо",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "food_173",
        "text": "После жирного боль в спину, рвота и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_174",
        "text": "После еды спутанность и слабость",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "food_175",
        "text": "После подозрительной шаурмы рвота и понос целый день",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["infectious_pattern_if_acute", "urgent_general_route"],
        "expected_care_level_any": ["urgent", "routine_doctor"],
    },
    {
        "id": "food_176",
        "text": "После еды очень сильная боль вверху живота",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_177",
        "text": "После еды черный стул, но боли почти нет",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "food_178",
        "text": "После еды рвота, температура и слабость",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_179",
        "text": "После жирной еды боль справа и не могу пить воду",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_180",
        "text": "После еды кровь в стуле и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },

    # MIXED / EDGE
    {
        "id": "food_181",
        "text": "После вина и сыра тяжесть в желудке и жжение",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia", "histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_182",
        "text": "После молока и сладкого слабость и бурлит живот",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "carbohydrate_malabsorption_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_183",
        "text": "После сладкого и жирного тяжесть, дурнота и сонливость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_184",
        "text": "После сыра и молока вздутие и головная боль",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_185",
        "text": "После бобовых и жирного тянет живот и слабость",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_186",
        "text": "После поздней жирной еды изжога и тяжесть справа",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_187",
        "text": "После кофе, сладкого и молока дурнота и вздутие",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "carbohydrate_malabsorption_pattern", "sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_188",
        "text": "После алкоголя и копченостей жжение и головная боль",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "alcohol_related_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_189",
        "text": "После молочного и бобовых раздуло живот и слабость",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_190",
        "text": "После жирного и сладкого одновременно болит голова и тяжесть",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },

    # FALSE-POSITIVE DEFENSE / non-histamine defaults / non-IBS one-off
    {
        "id": "food_191",
        "text": "После одного раза с молоком был жидкий стул",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_192",
        "text": "После одного раза с луком было вздутие",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_193",
        "text": "После вина просто тошнит немного",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_194",
        "text": "После сыра один раз заболела голова без покраснения",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload", "histamine_conditional_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_195",
        "text": "После еды один раз вздутие и урчание",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["simple_overeating_or_fast_eating", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_196",
        "text": "После еды один раз тяжесть и отрыжка",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_197",
        "text": "После жирной еды один раз сонливость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_198",
        "text": "После молока было плохо впервые в жизни",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_199",
        "text": "После большого обеда отрыжка и тяжесть первый раз",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["simple_overeating", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_200",
        "text": "После сладкого и жирного стало дурно первый раз",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload", "sugar_glucose_pattern"],
        "expected_care_level_any": ["home"],
    },
]

