from __future__ import annotations


REGRESSION_CASES_FOOD_HARD_100 = [
    # =========================================================
    # 001-020 MIXED FATTY / SWEET / SYSTEMIC / GI
    # =========================================================
    {
        "id": "hard_001",
        "text": "После жирного и сладкого мутит, тяжесть и как будто сахар качает",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_002",
        "text": "После торта и шашлыка тяжело в желудке, слабость и хочется лечь",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["simple_overeating", "postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_003",
        "text": "После жареного мяса и сладкой газировки тошнит и кружится голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_004",
        "text": "После жирного вроде тошнит, а вроде больше слабость и сонливость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_005",
        "text": "После жирного и десерта давит под ложечкой и мутновато в голове",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_006",
        "text": "После картошки фри и торта то тяжесть, то дрожь",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_007",
        "text": "После жирного вроде желудок полный, но больше накрывает слабость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_008",
        "text": "После бургера, картошки и сладкого хочется спать и мутит",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload", "sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_009",
        "text": "После еды вроде не больно, но очень тяжело и тошнит",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating", "fatty_food_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_010",
        "text": "После сладкого и жирного голова болит, а в животе просто тяжесть",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_011",
        "text": "После обильного ужина не пойму что больше — тошнота или слабость",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["simple_overeating", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_012",
        "text": "После жирной еды и сладкого мутит уже второй раз за неделю",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_013",
        "text": "После плотной еды тяжесть, но иногда еще бросает в пот",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "sugar_glucose_pattern", "simple_overeating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_014",
        "text": "После жирного мутит и кружится голова, но боли нет",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_015",
        "text": "После сладкого после еды дрожь, но и желудок как переполнен",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "simple_overeating", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_016",
        "text": "После бургеров и мороженого урчит, слабость и хочется лечь",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "hard_017",
        "text": "После жирного тошнота, а потом слабость и потливость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_018",
        "text": "После еды ощущение как интоксикация, но скорее просто жирного перебрал",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_019",
        "text": "После жареного тяжесть, дурнота и потом отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_020",
        "text": "После сладкого на фоне жирного как будто и сахар, и желудок вместе",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },

    # =========================================================
    # 021-040 HISTAMINE FALSE POSITIVES / TRUE POSITIVES
    # =========================================================
    {
        "id": "hard_021",
        "text": "После сыра просто заболела голова один раз",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_022",
        "text": "После вина немного мутит, но без покраснения и без сердца",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_023",
        "text": "После сыра и вина уже несколько раз голова, краснею и сердце колотится",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_024",
        "text": "После копченостей голова болит, но больше из за того что не спал",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_025",
        "text": "После вина, сыра и колбасы голова, нос закладывает и лицо горит",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_026",
        "text": "После одного бокала вина сердце бьется и жарко",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "hard_027",
        "text": "После шампанского, сыра и копченостей прям краснею и болит голова",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_028",
        "text": "После сыра и вина только слабость без головы и кожи",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_029",
        "text": "После колбасы и сыра лицо горит, нос заложен и сердцебиение",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_030",
        "text": "После вина головная боль и слабость уже не первый раз",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_031",
        "text": "После сыра тяжесть в желудке и немного тошнит",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_032",
        "text": "После копченостей один раз заболела голова без других симптомов",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "histamine_conditional_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_033",
        "text": "После вина краснею и сердце колотится почти всегда",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_034",
        "text": "После сыра и шампанского голова, покраснение, жар и нос",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_035",
        "text": "После алкоголя болит голова и сушит",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "dehydration_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_036",
        "text": "После красного вина лицо горит уже третий раз подряд",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_037",
        "text": "После сыра слабость и сонливость, но без типичных аллергических признаков",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_038",
        "text": "После вина и сыра жжение в груди и кислота",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_039",
        "text": "После одного бокала вина немного кружится голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_040",
        "text": "После копченостей и шампанского краснота, сердце и головная боль",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },

    # =========================================================
    # 041-060 IBS FALSE POSITIVE DEFENSE / ONE-OFF BOWEL
    # =========================================================
    {
        "id": "hard_041",
        "text": "После одного раза с фасолью вздуло живот",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_042",
        "text": "После одной пиццы был жидкий стул и урчание",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["simple_overeating_or_fast_eating", "fatty_food_overload", "dairy_lactose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_043",
        "text": "После еды иногда вздувает, но это нечасто",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["simple_overeating_or_fast_eating", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_044",
        "text": "После молока один раз был понос, раньше не было",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_045",
        "text": "После лука и чеснока один раз сильно пучило",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_046",
        "text": "Живот урчит после еды время от времени, без боли",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["simple_overeating_or_fast_eating", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_047",
        "text": "После еды иногда газы и вздутие, но стул нормальный",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["simple_overeating_or_fast_eating", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_048",
        "text": "После еды уже давно крутит живот и то понос то запор",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_049",
        "text": "После еды часто вздутие и нестабильный стул уже много месяцев",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_050",
        "text": "После молочного и лука часто вздутие и меняется стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_051",
        "text": "После еды то бурлит, то нормально, но уже давно",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_052",
        "text": "После еды нестабильный стул и вздутие каждую неделю",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_053",
        "text": "После яблок, сока и меда то понос, то вздутие постоянно",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_054",
        "text": "После еды крутит живот давно, но без температуры и крови",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_055",
        "text": "После еды газы и урчание почти каждый день",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_056",
        "text": "После одного молочного коктейля раздуло живот и газы",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_057",
        "text": "После салата с луком и фасолью вздутие, но это было один раз",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_058",
        "text": "После разных продуктов уже давно урчание и вздутие",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_059",
        "text": "После молочного иногда нормально, а иногда сильно вздувает",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_060",
        "text": "После яблочного сока и йогурта бурлит и понос",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },

    # =========================================================
    # 061-080 URGENT EDGE / PANCREATIC / BLEED / CARDIAC LOOK-ALIKE
    # =========================================================
    {
        "id": "hard_061",
        "text": "После жирного сильная боль вверху живота и рвота",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "hard_062",
        "text": "После еды боль под ложечкой, температура и рвота",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "hard_063",
        "text": "После шашлыка боль вверху живота отдает в спину",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["pancreatic_warning_if_severe", "biliary_pattern", "urgent_general_route"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "hard_064",
        "text": "После еды черный стул и слабость, боли почти нет",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "hard_065",
        "text": "После еды кровь в рвоте и жжение до этого",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "hard_066",
        "text": "После позднего ужина боль в груди и жжение",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route", "reflux_pattern"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "hard_067",
        "text": "После еды сильная слабость и одышка",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "hard_068",
        "text": "После жирного резкая боль справа, рвота и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "hard_069",
        "text": "После жирной еды сильная боль и не могу пить воду",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "hard_070",
        "text": "После еды обморок, до этого было мутно",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "hard_071",
        "text": "После еды кровь в стуле и температура 38",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "hard_072",
        "text": "После жирного боль в спину, слабость и многократная рвота",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route", "pancreatic_warning_if_severe"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "hard_073",
        "text": "После еды жжение в груди и не хватает воздуха",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "hard_074",
        "text": "После еды сильная боль в верхней части живота без рвоты",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route", "pancreatic_warning_if_severe"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "hard_075",
        "text": "После еды черный стул и головокружение",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
    {
        "id": "hard_076",
        "text": "После еды боль в груди, но кажется это изжога",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route", "reflux_pattern"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "hard_077",
        "text": "После еды температура и сильная слабость, поноса нет",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "hard_078",
        "text": "После еды желтуха и боль справа под ребром",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route", "biliary_pattern"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "hard_079",
        "text": "После подозрительной еды слабость, понос, но еще и кровь в стуле",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "hard_080",
        "text": "После еды спутанность и очень плохо",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },

    # =========================================================
    # 081-100 MESSY REAL-WORLD LANGUAGE / SLANG / DIRTY INPUT
    # =========================================================
    {
        "id": "hard_081",
        "text": "че то после жирного меня прям накрывает и мутно",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_082",
        "text": "после молочки меня раздувает как шар и бурлит",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_083",
        "text": "после жареного как камень в желудке",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_084",
        "text": "после сладкого прям трусит и в пот кидает",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_085",
        "text": "после вина лицо в жар и башка трещит",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_086",
        "text": "после еды че то в правом боку сверху тянет и горчит",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_087",
        "text": "после еды крутит кишки и стул вообще плавает",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_088",
        "text": "после позднего хавчика кислота обратно идет",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_089",
        "text": "после жирного справа под ребрами ноет уже который раз",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_090",
        "text": "после молока сдуру выпил стакан и потом понесло",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_091",
        "text": "после бургера и колы будто сахар скакнул и желудок встал",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_092",
        "text": "после шампусика и сыра красный как помидор",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_093",
        "text": "после хавки жесть как хочется лечь и мозги ватные",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_094",
        "text": "после чеснока и фасоли живот как шар и газы адские",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "hard_095",
        "text": "после жирняка прям справа колет и горчит",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_096",
        "text": "после еды изжога прям поднимается в горло",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "hard_097",
        "text": "после молочки живот бурлит капец и стул жидкий",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "hard_098",
        "text": "после еды как будто сейчас вырубит",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "hard_099",
        "text": "после жирного спина тянет и мутит",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "pancreatic_warning_if_severe", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "hard_100",
        "text": "после хавки кровь в стуле это уже не шутки",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
]

