"""
Реестр фич по тарифам: FREE, PLUS, PRO, FAMILY, CLINIC.
"""
from __future__ import annotations

from typing import Dict, List, Set

# Ключи фич
FEATURE_SYMPTOM_CHAT_BASIC = "symptom_chat_basic"
FEATURE_EMERGENCY_TRIAGE = "emergency_triage"
FEATURE_LAB_INTERPRETATION_BASIC = "lab_interpretation_basic"
FEATURE_CARE_PLAN_SHORT = "care_plan_short"
FEATURE_MEMORY_LIMITED = "memory_limited"

FEATURE_CHAT_UNLIMITED = "chat_unlimited"
FEATURE_LAB_INTERPRETATION_UNLIMITED = "lab_interpretation_unlimited"
FEATURE_USER_REPORT_STRUCTURED = "user_report_structured"
FEATURE_CONTINUITY_SUMMARY = "continuity_summary"
FEATURE_FOLLOWUP_SUPPORT = "followup_support"
FEATURE_TRENDS_BASIC = "trends_basic"

FEATURE_PHYSICIAN_REPORT = "physician_report"
FEATURE_LAB_INTERPRETATION_ADVANCED = "lab_interpretation_advanced"
FEATURE_MULTI_DOCUMENT_ANALYSIS = "multi_document_analysis"
FEATURE_MEMORY_LONG = "memory_long"
FEATURE_CARE_PATHWAYS_ADVANCED = "care_pathways_advanced"
FEATURE_REPORT_EXPORT = "report_export"
FEATURE_FAMILY_PROFILES_OPTIONAL = "family_profiles_optional"

FEATURE_FAMILY_MULTI_PROFILE = "family_multi_profile"
FEATURE_FAMILY_PARENT_ELDER = "family_parent_elder"
FEATURE_FAMILY_SHARED_REPORTS = "family_shared_reports"

FEATURE_CLINIC_PHYSICIAN_MODE = "clinic_physician_mode"
FEATURE_CLINIC_BRANDED_REPORTS = "clinic_branded_reports"
FEATURE_CLINIC_API_WEBHOOK = "clinic_api_webhook"
FEATURE_CLINIC_DASHBOARD_EXPORTS = "clinic_dashboard_exports"
FEATURE_CLINIC_VOLUME_USAGE = "clinic_volume_usage"

# По тарифам: какие фичи включены (без лимитов; лимиты в планах)
TIER_FEATURES: Dict[str, List[str]] = {
    "free": [
        FEATURE_SYMPTOM_CHAT_BASIC,
        FEATURE_EMERGENCY_TRIAGE,
        FEATURE_LAB_INTERPRETATION_BASIC,
        FEATURE_CARE_PLAN_SHORT,
        FEATURE_MEMORY_LIMITED,
    ],
    "plus": [
        FEATURE_SYMPTOM_CHAT_BASIC,
        FEATURE_EMERGENCY_TRIAGE,
        FEATURE_LAB_INTERPRETATION_BASIC,
        FEATURE_CARE_PLAN_SHORT,
        FEATURE_MEMORY_LIMITED,
        FEATURE_CHAT_UNLIMITED,
        FEATURE_LAB_INTERPRETATION_UNLIMITED,
        FEATURE_USER_REPORT_STRUCTURED,
        FEATURE_CONTINUITY_SUMMARY,
        FEATURE_FOLLOWUP_SUPPORT,
        FEATURE_TRENDS_BASIC,
    ],
    "pro": [
        FEATURE_SYMPTOM_CHAT_BASIC,
        FEATURE_EMERGENCY_TRIAGE,
        FEATURE_LAB_INTERPRETATION_BASIC,
        FEATURE_CARE_PLAN_SHORT,
        FEATURE_MEMORY_LIMITED,
        FEATURE_CHAT_UNLIMITED,
        FEATURE_LAB_INTERPRETATION_UNLIMITED,
        FEATURE_USER_REPORT_STRUCTURED,
        FEATURE_CONTINUITY_SUMMARY,
        FEATURE_FOLLOWUP_SUPPORT,
        FEATURE_TRENDS_BASIC,
        FEATURE_PHYSICIAN_REPORT,
        FEATURE_LAB_INTERPRETATION_ADVANCED,
        FEATURE_MULTI_DOCUMENT_ANALYSIS,
        FEATURE_MEMORY_LONG,
        FEATURE_CARE_PATHWAYS_ADVANCED,
        FEATURE_REPORT_EXPORT,
        FEATURE_FAMILY_PROFILES_OPTIONAL,
    ],
    "family": [
        FEATURE_SYMPTOM_CHAT_BASIC,
        FEATURE_EMERGENCY_TRIAGE,
        FEATURE_LAB_INTERPRETATION_BASIC,
        FEATURE_CARE_PLAN_SHORT,
        FEATURE_CHAT_UNLIMITED,
        FEATURE_LAB_INTERPRETATION_UNLIMITED,
        FEATURE_USER_REPORT_STRUCTURED,
        FEATURE_CONTINUITY_SUMMARY,
        FEATURE_FOLLOWUP_SUPPORT,
        FEATURE_TRENDS_BASIC,
        FEATURE_PHYSICIAN_REPORT,
        FEATURE_FAMILY_MULTI_PROFILE,
        FEATURE_FAMILY_PARENT_ELDER,
        FEATURE_FAMILY_SHARED_REPORTS,
    ],
    "clinic": [
        FEATURE_SYMPTOM_CHAT_BASIC,
        FEATURE_EMERGENCY_TRIAGE,
        FEATURE_LAB_INTERPRETATION_BASIC,
        FEATURE_CARE_PLAN_SHORT,
        FEATURE_CHAT_UNLIMITED,
        FEATURE_LAB_INTERPRETATION_UNLIMITED,
        FEATURE_USER_REPORT_STRUCTURED,
        FEATURE_CONTINUITY_SUMMARY,
        FEATURE_FOLLOWUP_SUPPORT,
        FEATURE_TRENDS_BASIC,
        FEATURE_PHYSICIAN_REPORT,
        FEATURE_CLINIC_PHYSICIAN_MODE,
        FEATURE_CLINIC_BRANDED_REPORTS,
        FEATURE_CLINIC_API_WEBHOOK,
        FEATURE_CLINIC_DASHBOARD_EXPORTS,
        FEATURE_CLINIC_VOLUME_USAGE,
    ],
}


def get_features_for_tier(tier: str) -> Set[str]:
    return set(TIER_FEATURES.get(tier.lower(), TIER_FEATURES["free"]))
