from __future__ import annotations


REGRESSION_CASES_FOOD_LARGE = [
    # =========================
    # FATTY / FRIED / SYSTEMIC
    # =========================
    {
        "id": "food_001",
        "text": "После жареной картошки и семечек подташнивает и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_002",
        "text": "После жирной еды слабость, сонливость и дурнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_003",
        "text": "После шашлыка и майонеза тяжесть и тошнота",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_004",
        "text": "После бургеров и чипсов болит голова и мутит",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["fatty_food_systemic_overload", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_005",
        "text": "После очень жирного ужина переполненность, тяжесть и отрыжка",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_006",
        "text": "После жареного мяса и семечек ватное состояние и подташнивает",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_007",
        "text": "После фастфуда слабость и тянет ко сну",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_008",
        "text": "После жирной и жареной еды тяжесть вверху живота и тошнота",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["fatty_food_overload", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    # =========================
    # BILIARY / RUQ
    # =========================
    {
        "id": "food_009",
        "text": "После жирного тянет справа под ребром и горечь во рту",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_010",
        "text": "После жареной еды тяжесть справа под ребрами и тошнота",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_011",
        "text": "После масла и жирного сыра болит справа под ребром",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "urgent"],
    },
    {
        "id": "food_012",
        "text": "После жирного мутит, горечь во рту и неприятно справа",
        "recurrent": False,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern", "fatty_food_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_013",
        "text": "После шашлыка боль справа под ребром и отдаёт в спину",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_014",
        "text": "После жирной еды сильная боль справа под ребром и температура",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent", "emergency"],
    },
    {
        "id": "food_015",
        "text": "После жирного снова тяжесть справа под ребром",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_016",
        "text": "После жареной картошки и яиц тянет справа и горечь",
        "recurrent": True,
        "expected_zone": "right_upper_abdominal_zone",
        "expected_top_causes_any": ["biliary_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    # =========================
    # REFLUX / UPPER GI
    # =========================
    {
        "id": "food_017",
        "text": "После позднего ужина жжение, кислая отрыжка и хуже когда ложусь",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_018",
        "text": "После еды изжога и кислый привкус во рту",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_019",
        "text": "После жирного жжение за грудиной и отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_020",
        "text": "После плотного ужина переполненность, отрыжка и жжение",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern", "functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_021",
        "text": "После кофе и позднего ужина кислота и жжение в груди",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_022",
        "text": "После еды тяжесть под ложечкой и отрыжка",
        "recurrent": False,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia", "simple_overeating"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_023",
        "text": "После небольшой еды быстрое насыщение и тяжесть",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["functional_dyspepsia"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_024",
        "text": "Ночью после еды жжение и кислая отрыжка",
        "recurrent": True,
        "expected_zone": "upper_gi_zone",
        "expected_top_causes_any": ["reflux_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    # =========================
    # DAIRY
    # =========================
    {
        "id": "food_025",
        "text": "После молока и мороженого раздуло живот, урчит и жидкий стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_026",
        "text": "После творога вздутие и газы",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_027",
        "text": "После сливок и молочного коктейля урчание и понос",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_028",
        "text": "После йогурта вздуло живот и подташнивает",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_029",
        "text": "После молока крутит живот и жидкий стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_030",
        "text": "После мороженого живот бурлит и много газов",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern", "simple_overeating_or_fast_eating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_031",
        "text": "После творога каждый раз вздутие и урчание",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_032",
        "text": "После молочного стало плохо уже несколько раз",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["dairy_lactose_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    # =========================
    # FODMAP / CARB
    # =========================
    {
        "id": "food_033",
        "text": "После лука и чеснока сильное вздутие и газы",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_034",
        "text": "После бобовых урчит, пучит и послабление стула",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_035",
        "text": "После яблочного сока вздутие и понос",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_036",
        "text": "После меда и фруктов бурлит живот и много газов",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["carbohydrate_malabsorption_pattern", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_037",
        "text": "После фасоли вздутие и урчание весь вечер",
        "recurrent": False,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_038",
        "text": "После лука, чеснока и бобовых каждый раз раздувает живот",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    # =========================
    # IBS-LIKE / RECURRENT BOWEL
    # =========================
    {
        "id": "food_039",
        "text": "У меня часто после еды вздутие и постоянно меняется стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_040",
        "text": "Уже давно после разных продуктов вздутие и то запор то понос",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_041",
        "text": "Каждую неделю после еды крутит живот и меняется стул",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent"],
        "expected_care_level_any": ["routine_doctor"],
    },
    {
        "id": "food_042",
        "text": "Давно повторяется вздутие и нестабильный стул после еды",
        "recurrent": True,
        "expected_zone": "bowel_zone",
        "expected_top_causes_any": ["ibs_pattern_if_recurrent", "fodmap_fermentation_pattern"],
        "expected_care_level_any": ["routine_doctor"],
    },
    # =========================
    # HISTAMINE / ALCOHOL
    # =========================
    {
        "id": "food_043",
        "text": "После вина и сыра болит голова, краснеет лицо и сердце колотится",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_044",
        "text": "После копченостей и вина головная боль и покраснение лица",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_045",
        "text": "После шампанского и сыра тошнит, сердце стучит и жарко",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern", "alcohol_related_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_046",
        "text": "После колбасы и вина болит голова и закладывает нос",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["histamine_conditional_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_047",
        "text": "После алкоголя тошнота и головная боль",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_048",
        "text": "После пива слабость и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["alcohol_related_pattern", "dehydration_pattern"],
        "expected_care_level_any": ["home"],
    },
    # =========================
    # SWEET / GLUCOSE
    # =========================
    {
        "id": "food_049",
        "text": "После сладкого резко слабость, дрожь и потливость",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    {
        "id": "food_050",
        "text": "После торта дурнота и кружится голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_051",
        "text": "После сладкой газировки слабость и тошнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_052",
        "text": "После десерта после жирной еды мутит и дрожь",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["sugar_glucose_pattern", "fatty_food_systemic_overload"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    # =========================
    # DEHYDRATION / VASCULAR
    # =========================
    {
        "id": "food_053",
        "text": "После еды слабость, сухость во рту и болит голова",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["dehydration_pattern", "postprandial_vascular_pattern"],
        "expected_care_level_any": ["home", "routine_doctor"],
    },
    {
        "id": "food_054",
        "text": "После плотной еды ватное состояние и хочется лечь",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_055",
        "text": "После большого обеда слабость, сонливость и дурнота",
        "recurrent": False,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "simple_overeating"],
        "expected_care_level_any": ["home"],
    },
    {
        "id": "food_056",
        "text": "После еды кружится голова и подташнивает, боли нет",
        "recurrent": True,
        "expected_zone": "systemic_zone",
        "expected_top_causes_any": ["postprandial_vascular_pattern", "dehydration_pattern"],
        "expected_care_level_any": ["routine_doctor", "home"],
    },
    # =========================
    # ACUTE / INFECTIOUS / URGENT
    # =========================
    {
        "id": "food_057",
        "text": "Рвота, понос, температура после подозрительной еды",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_058",
        "text": "После салата начались рвота и понос, температура 38",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["urgent"],
    },
    {
        "id": "food_059",
        "text": "Сильная боль в животе, черный стул и слабость",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency", "urgent"],
    },
    {
        "id": "food_060",
        "text": "После еды боль в груди и одышка",
        "recurrent": False,
        "expected_zone": "urgent_route",
        "expected_top_causes_any": ["urgent_general_route"],
        "expected_care_level_any": ["emergency"],
    },
]

